### ISSUE TITLE
(refactor) Service: Enhance the functionality of the services.

### ISSUE THREAD

**Issue by hastebrot** [TestFX/TestFX#167]
- [x] `finder.NodeFinder` needs to be able to return invisible `Node`s. Introducing a `NodeQuery` could help to keep the interface simple (#174, #205).
- [x] `finder.WindowFinder` needs to be able to accept `Node`s in `target()` and `window()` (#238).
- [ ] `locator.PointLocator` needs to be able to return coordinates relative to the `Scene` and the `Screen` (#194, #206).
- [x] `support.CaptureSupport` needs to be able to capture certain `Bounds`, draw `Rectangle`s into the `Image`s and add text of `AssertionError` to the `Image`s.
- [x] `support.WaitUntilSupport` needs to be able to use `WaitForAsyncUtils` instead of the deprecated `FXTestUtils`.
